language: node_js
os:
  - osx
  - linux
  - windows
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "MC5FaHSphSi3qKyiHHBbAV5ELmeeH00KdEgUEvYG17YMzKUBv99Y/x9kzhUZ1xOtpmeZiSAx5KefgjJl9Ek4AyNvmKuFxQzXMn5DYAuRwA17dzsMrhREyw9FDJbFnAuQ8Be1SFhwf9GzC3I5REF+DibHJGrsq3JYs4nia0T/ERNQCaXMUUmYvQJDGTl//Ew/79fEzF6ZLQQ1sud7R4XokVx6p32IGcdjjx05MmfrjWbC+RaTZO/RmpBDFhqtv/3yQyHpJoPygyKz9tsQntOrDvY7SrxMiHRp+hACQ7ljeiY3tZHursZAhzTZFvR3JbpexWUTV447Y9dLBzYJmoahtsiKRgaRIp8VCFYymh0Gyi2JQctYRCnrBl1vTKqaGRzVkg4QtAjpLpfEl95EdlxKtw8C5FFu6FqZEDzRaonkbFytHdVis3GgLvrrRtud+3VVTg9jX4Y4sfmWCazrRUrzrBV0OQlVcTBEtNDuRkPI3RcqQGOKJfLHHVuUVmyANqUelAyftfb4vn8e9zezacEgppSFyRvA5ke2lWvZa7LaI+6hU1HI5p1pQUHDqjyOrjjVv1aJE486SIG6f3yLAAc3yBlNF4Mr0qZflN0EgvCf20sxeDi/44r4yQTImklhq77ZsHJlmLjNL6xQYfRAPmI/HI7HZw2LdLXsmyJ3bw4/TaU="
  api_key: # 15df
    secure: "CJDzN6VUdiBvSwx9o6GmyscvyXqfZ6WMlbqHmGavRxW0UreDR046q72GOYJMhh7xg7wwx+2DbLkHxd03qYxHZJeDoCxPg488B3fUTIZNgA3iNPTF9v7cfGAl/fXk+/y/3taiU3b7R1q8xL9b9fbbLdocnfWNjrVBR0IWbEl4xJt3t6nlA49P6AVC3p1hUKFtJj+2efEAF+KwKmSnNUG72MmIzWn9W4mCtPpdpp4jqv2kmaP5RYYcyMzdGot/mjkBnmgcmdy7ofkoZ52lMASBQwThMJ5Pf3oRTUQggg8YusXMQBCYy/EBWPNRZx7yjs9q9vj9foTpI0XdIY9D4Y6E2fljeDGwx7yukwAPKNgRyarOTyKRN5I71T1pTwKrUXRBICfWRkzRPgHgmqQDUKNPM20NmcS6jgAlh2tKkefHKQWr/V/5O9GrMBxnW0RDamQsQ/MSJZ7d65/QglKLDTRELDfDQGEotE1dJb6pu/IZObZ3kP4be5Zq5O1vNieLP5K2EMnpkqoVQK+KN4QmOLA8jTEFAxKTnFQvnS+pn4kGU8p25eh69AcDkh5/6t5Z/55PTuKlxIxKouHKBeJ5hSmoHmtdbBL+xHj7zAfJ6W3R2Ld1zKK1cPeYQwmN0YgynKWyiOMqx4+gK2AjsY3YhUBU7CPf7tgRRn3AMUqxecnDDL0="
  on:
    tags: true
    node: lts/*
